DEFAULT: &default
	DEBUG = False
	TESTING = False
	DATABASE_URI = None

DEVELOPMENT: &development
	<<: *default
	DEBUG = True
	DATABASE_URI = mysql://dev:26aes37b4@127.0.0.1/rivershout_dev

TESTING: &testing
	<<: *default
	TESTING = True
	DATABASE_URI = mysql://dev:26aes37b4@127.0.0.1/rivershout_test

