DEFAULT: &default
    DEBUG: False
    TESTING: False
    DATABASE_URI: None

DEVELOPMENT: &development
    <<: *default
    DEBUG: True
    DATABASE_URI: "mysql://root:1234@127.0.0.1/dev_db"

TESTING: &testing
    <<: *default
    TESTING: True
    DATABASE_URI: "mysql://root:1234@127.0.0.1/test_db"

